services:
  - type: web
    name: onudhabon-web
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: onudhabon
      - key: GEMINI_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SSLC_STORE_ID
        sync: false
      - key: SSLC_STORE_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: "Onudhabon <onboarding@resend.dev>"
      - key: GOOGLE_SCRIPT_URL
        sync: false
