// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onudhabon_ISD.Data;

#nullable disable

namespace Onudhabon_ISD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822155100_DropLocalGuardiansAndSeedClassPlans")]
    partial class DropLocalGuardiansAndSeedClassPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Onudhabon_ISD.Models.ClassPlan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClassLevel")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Subjects")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("ClassPlans", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        ClassLevel = "1",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla\",\"totalLectures\":10},{\"name\":\"English\",\"totalLectures\":10},{\"name\":\"Math\",\"totalLectures\":10}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 2,
                        ClassLevel = "2",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla\",\"totalLectures\":10},{\"name\":\"English\",\"totalLectures\":10},{\"name\":\"Math\",\"totalLectures\":10}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 3,
                        ClassLevel = "3",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla\",\"totalLectures\":10},{\"name\":\"English\",\"totalLectures\":10},{\"name\":\"Math\",\"totalLectures\":10}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 4,
                        ClassLevel = "4",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 5,
                        ClassLevel = "5",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 6,
                        ClassLevel = "6",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 7,
                        ClassLevel = "7",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 8,
                        ClassLevel = "8",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 9,
                        ClassLevel = "9",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12},{\"name\":\"Physics\",\"totalLectures\":12},{\"name\":\"Chemistry\",\"totalLectures\":12},{\"name\":\"Higher Math\",\"totalLectures\":12},{\"name\":\"Biology\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 10,
                        ClassLevel = "10",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":12},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":12},{\"name\":\"English 1st paper\",\"totalLectures\":12},{\"name\":\"English 2nd paper\",\"totalLectures\":12},{\"name\":\"Math\",\"totalLectures\":12},{\"name\":\"Social Science\",\"totalLectures\":12},{\"name\":\"General Science\",\"totalLectures\":12},{\"name\":\"Physics\",\"totalLectures\":12},{\"name\":\"Chemistry\",\"totalLectures\":12},{\"name\":\"Higher Math\",\"totalLectures\":12},{\"name\":\"Biology\",\"totalLectures\":12}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 11,
                        ClassLevel = "11",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":20},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":20},{\"name\":\"English 1st paper\",\"totalLectures\":20},{\"name\":\"English 2nd paper\",\"totalLectures\":20},{\"name\":\"Physics 1st paper\",\"totalLectures\":20},{\"name\":\"Physics 2nd paper\",\"totalLectures\":20},{\"name\":\"Chemistry 1st paper\",\"totalLectures\":20},{\"name\":\"Chemistry 2nd paper\",\"totalLectures\":20},{\"name\":\"Higher Math 1st paper\",\"totalLectures\":20},{\"name\":\"Higher Math 2nd paper\",\"totalLectures\":20},{\"name\":\"Biology 1st paper\",\"totalLectures\":20},{\"name\":\"Biology 2nd paper\",\"totalLectures\":20}]",
                        __v = 0
                    },
                    new
                    {
                        Id = 12,
                        ClassLevel = "12",
                        CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        Subjects = "[{\"name\":\"Bangla 1st paper\",\"totalLectures\":20},{\"name\":\"Bangla 2nd paper\",\"totalLectures\":20},{\"name\":\"English 1st paper\",\"totalLectures\":20},{\"name\":\"English 2nd paper\",\"totalLectures\":20},{\"name\":\"Physics 1st paper\",\"totalLectures\":20},{\"name\":\"Physics 2nd paper\",\"totalLectures\":20},{\"name\":\"Chemistry 1st paper\",\"totalLectures\":20},{\"name\":\"Chemistry 2nd paper\",\"totalLectures\":20},{\"name\":\"Higher Math 1st paper\",\"totalLectures\":20},{\"name\":\"Higher Math 2nd paper\",\"totalLectures\":20},{\"name\":\"Biology 1st paper\",\"totalLectures\":20},{\"name\":\"Biology 2nd paper\",\"totalLectures\":20}]",
                        __v = 0
                    });
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.Forum", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Author")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Content")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("Replies")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("Tags")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("Forums", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.ForumPost", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Author")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Content")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("Replies")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("Tags")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("ForumPosts", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.Lecture", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClassLevel")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("Instructor")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Status")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<string>("Subject")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Thumbnail")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Topic")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Version")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("VideoUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("Lectures", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.Material", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClassLevel")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("Date")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("Downloads")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("FileUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Instructor")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Size")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Status")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<string>("Subject")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Topic")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Version")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("Materials", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.Notification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<bool>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("Post")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Sender")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Type")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("User")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("Notifications", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.Student", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("BirthCertificateId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ClassLevel")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("CompletedClasses")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("ConsentLetterUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("EnrollmentYear")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("FatherName")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("GuardianId")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("GuardianName")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("MotherName")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Status")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<string>("Subjects")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.ToTable("Students", (string)null);
            });

            modelBuilder.Entity("Onudhabon_ISD.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("Age")
                    .HasColumnType("int");

                b.Property<bool>("AgreeToTerms")
                    .HasColumnType("bit");

                b.Property<string>("Area")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Bio")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("CertificatePicture")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("CurrentlyStudying")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("EducationLevel")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("HscInstitute")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("HscPassingYear")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Institution")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsRestricted")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<bool>("IsVerified")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("Location")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Major")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("NidNumber")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Picture")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("SscInstitute")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("SscPassingYear")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("UniversityName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("UniversityPassingYear")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("VerificationStatus")
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Pending");

                b.Property<string>("VolunteerReason")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int?>("__v")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}